import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";

import BlogCard from "../components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-eu-central-1.graphcms.com/v2/cl4birevw30xr01w85ys1hg4e/master"
);

const QUERY = gql`
  {
    posts {
      title
      id
      date_published
      slug
      content {
        html
      }

      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;
export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            key={post.id}
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            datePublished={post.date_published}
            slug={post.slug}
            content={post.content}
          />
        ))}
      </main>
    </div>
  );
}
